apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: pizza
  labels:
    app: inventory-service
  annotations:
    prometheus.io/path: /actuator/prometheus                                                                                                                                                                                                                                 │
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 9004
    protocol: TCP
  selector:
    app: inventory-service
